### ISSUE TITLE
[BUG] $PATH is not correctly set up

### ISSUE THREAD

**Issue by BenediktFloeser** [atuinsh/desktop#233]
## Bug Description
I configured zsh as my default shell for scripts. I have various cli tools installed via brew and mise, however Atuin cannot find these. 

## Steps to Reproduce
1. Install terragrunt via mise system-wide
2. Create Atuin runbook 
3. Add a script that calls terragrunt
4. See error: zsh cannot find terragrunt

## Expected Behavior
I would like Atuin to pick up the $PATH where all of the executables I need are stored.

## Actual Behavior
Apparently, the $PATH is not set correctly so various executables are not found.

## Environment
- **OS**: Ubuntu 24.04
- **Atuin Desktop Version**: 0.1.11 amd64
- **Atuin CLI Version**: 18.10.0
- **Shell**: zsh
- **Terminal**: Alacritty

## Additional Context
I use several executables from nonstandard sources (i.e. not from the official repos), namely brew and mise. These reside in non-standard paths and need to be included in $PATH via some mechanism.

## Workaround
For the time being, I am setting an environment variable called PATH at the start of each runbook where I paste the actual output of `echo $PATH` of my shell. In terms of collaboration this is not great, though.

**Comment by ellie** [comment]
This should be resolved as part of 0.2.0!

We now start up an interactive term while the app boots, and inherit the path from there. Additionally, terminals + shells _should_ be using login sessions. 

There are still a few edge cases that may remain here (as there are many places you can set a PATH), but I think we have squashed them all. 

If you could try the update and lmk if it's resolved for you, I'd really appreciate it!

**Comment by BenediktFloeser** [comment]
Thanks for the quick reply but unfortunately, the issue remains. I also tried setting the zsh installed from brew as the default shell for scripts but that produced the same issue.

**Comment by BenediktFloeser** [comment]
I'll be happy to provide more info or test anything, if that's any help

**Comment by BinaryMuse** [comment]
@BenediktFloeser Do you see any output in the logs regarding the environment import?

To check, you can launch the app on your terminal (assuming your app is in `/Applications/Atuin.app`):

```bash
ATUIN_LOG=debug /Applications/Atuin.app/Contents/MacOS/atuin-desktop
```

Near the top of the output, you should see some lines that look like this:

```
[2025-11-26T17:26:24.399918000Z][INFO][atuin_desktop::util] Loading environment from login shell: /bin/zsh
[2025-11-26T17:26:24.400513000Z][DEBUG][atuin_desktop::util] Attempting to capture environment with args: ["-l", "-c", "env"]
[2025-11-26T17:26:24.426001000Z][INFO][atuin_desktop::util] Loaded 4 environment variables from login shell. PATH: <your shell's default PATH>
```

**Comment by ellie** [comment]
I suspect this is the same as #261

**Comment by BenediktFloeser** [comment]
Yes, I think it is. I'll report back once I verified this.

**Comment by BenediktFloeser** [comment]
I tested this and it's indeed the same issue. I resolved it by moving the relevant sections in my `.zshrc` into `.zshenv` and `.zprofile`.
